---
title: "R Notebook"
output: html_notebook
author:
  - name: "Alonso Melgar López"
    url: https://github.com/alonmar
    
---

# Mis primeras lineas
Hola!!!

# Operaciones básicas
```{r}
# creamos variables
a <- 20
b <- 5

c <- a + b
c
```

```{r}
a - b
a * b
a / b

```

```{r}
#modulo
21%%7
```
# Clases primarias
## integer

```{r}
a <- 10L
b <- 3L

a+b
```

## numeric

```{r}
a <- 10.5
b <- 3.9
a+b
```

```{r}
4L + 10.5
```

## complex 

```{r}
a <- 6+5i
b <- 2+3i
a + b
```

## logical

```{r}

verdadero <- TRUE
falso <- FALSE

verdadero + falso

```

```{r}
falso + 2
```

## text, string, character

```{r}
text_doble <- "hola mundo"
text_simple <- 'hola mundo'
text_doble
text_simple
```

```{r}
#comillas sencillas dentro de comillas dobles
text_con_comillas <- "estas 'bien'? "
text_con_comillas
```

```{r}
# Concatenación de texto
txt <- "hola"
txt2 <- "mundo"

saludo <-  paste(txt, txt2)
saludo
```
## Tipos de objeto basicas
# vectores

```{r}
v_int <- c(2L, 4L, 6L  )
v_num <- c(2, 4.3, 5.9)
v_logico <- c("hola", FALSE, T, F)
v_logico
```

```{r}
x <- 1:5 # c(1, 2, 3, 4, 5)
y <- 7:11
x
y
```

```{r}
x + y
```

```{r}
sum(y)
mean(y)
```

## coerciones

```{r}
v <- c(2L, 1.5, 3.6)
v
```

```{r}
c(3.5, 3L, TRUE, "hi")
```

## Coerciones manuales

```{r}
x <- 0:6
#y <- as.numeric(x)
#y <- as.character(x)
y <- as.logical(x)
y
class(y)
```

```{r}
x <- c("a", "b", "c")
#y <- as.numeric(x)
y <- as.logical(x)
class(y)
```
# Estructuras de datos
## Matrices

```{r}
m <- matrix(1:20, nrow = 5, ncol = 4, byrow = FALSE )
m
```

## Dataframe

```{r}
primer_dataframe <- data.frame(x = 7:11,
                               y = c("a","b","c","d","e"))

primer_dataframe
```

```{r}
nrow(primer_dataframe)
ncol(primer_dataframe)
```

## list

```{r}
l <- list(1:10, "e", TRUE, primer_dataframe, NA)
l
```

## NA y NaN

```{r}
v <- c(2,3,NA,4,6)
sum(is.na(v))
```

```{r}
v <- c(3, 5, NaN, 6.7, NA)
is.nan(v)
```

# Subconjuntos

```{r}
v <- c("btc", "eth", "dash")
#v[3]
#v[c(TRUE, TRUE, FALSE)]
#v[-c(1,2)]
```
## vector
```{r}
m <- matrix(1:20, nrow = 4, ncol = 5)
m
```
## matrix

```{r}
#m[ , 2]
#m[,2:3] #c(1,2)


new_m <- m[ 1:3, 1:2]
new_m
```

## dataframe
```{r}
primer_dataframe$y
```

```{r}
# > mayor que
# < menor que
# <= menor igual que
# >= mayor igual que 
# == igual que
# != no igual que
result <- 3 != 3
result
```











