---
title: "R Notebook"
output: html_notebook
author:
  - name: "Alonso Melgar López"
    url: https://github.com/alonmar
    
---

# Estructuras de control

## if - else

```{r}
if(3>5){
  
  print("condicion verdadera")
  
}

```

```{r}
if(5>0){
  # verdadero
  print("esto es verdadero")
} else{
  # Falso
  print("esto es falso")
}
```

### ejemplo

```{r}
x <- runif(1, 0, 10)
x
```

```{r}
if(x > 3){
  # si x es mayor a 3 se ejecuta esto
  y <- 10
} else {
  # si x es menor a 3 se ejecuta esto
  y <- 0
}

y
```

# Ciclos

## ciclo for()

```{r}
# Se detiene hasta que se agoten los valores del vector
for (i in 1:5) {
  print(paste("el valor de i es:", i))
}
```

```{r}
frutas <- c("uva", "manzana", "pera", "naranja")
for (fruta in frutas) {
  print(fruta)
}
#for (i in 1:2) {
#  print(frutas[i*2])
#}
```

```{r}
for (i in 1:50) {
  
  if( i %% 10 == 0 ){
    print(paste("el valor de i es:", i))
  }
  
}


```

```{r}
for (i in 1:5) print(i)

```

```{r}
x <- 1:10

cuadrado <- matrix(0, nrow = 4, ncol = 4 )

for (i in 1:4) {
  
  cuadrado[i,i] <- x[i]*x[i]
  
}

print(cuadrado)
```

## while 

```{r}
contador <- 0
# Se detiene hasta que sea falso
while (contador < 10) {
  
  contador <- contador + 1
  print(paste("el valor de nuestro contador es:", contador))
}

print(paste("el valor final de nuestro contador es:", contador))
```

```{r}
z <- 0

while (z < 3) {
  
  moneda <- sample(0:1, 1)
  
  if(moneda > 0){
    #print("cara")
    z <- z + 1
  } else {
    #print("cruz")
    z <- z - 1
  }
  
}

print(z)

```

```{r}
sample(0:4, 10, replace = TRUE)
```

```{r}
frutas <- c("uva", "manzana", "pera", "naranja")

for (fruta in frutas) {
  
  print(fruta)
  if(fruta == "pera") {
    break
  }
  
  
}
```

```{r}
sumatoria <- 0

x <- 1:100

for (i in x) {
  sumatoria <- sumatoria + i
}

sumatoria
```

## multiples if - else

```{r}
frutas <- c("uva", "manzana", "pera", "naranja")

for (fruta in frutas) {
  
  if(fruta == "pera"){
    print("me encantas las peras")
  } else if (fruta == "uva") {
    print("no me gustan las uvas")
  } else if (fruta == "naranja"){
    print("me encantas las naranja")
  } else {
    print("no como frutas")
  }
  
}

```





















